### PR TITLE
Pycon US 2015 Tutorial (with Excellent Recording)

### PR DESCRIPTION
**Pull request by stonebig**

### CODE REVIEW

**Comment by jorisvandenbossche** [comment]
Maybe also mention the author/speaker and the repo with the material?

**Comment by stonebig** [comment]
let's try that (needs 5' to adapt to .rst)

**Comment by stonebig** [comment]
second try: as a student, I think:
-  I would like to know how much time it would take me seriously
- I would be glad if a free docker image already prepared was available: I don't know if it exists yet from Continuum io, Jupyter team, pydata.org or numfocus.

**Comment by jreback** [comment]
thanks...just noticed this :<

certainly welcome more updates!

**Comment by jreback** [comment]
website is updated

**Pull request closed without merging**
